<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start learning from best platform_query</name>
   <tag></tag>
   <elementGuidId>6928b0a3-0670-421b-9b26-2ac424bc5244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.search-box-shadow > div.input-group.search-box > input[name=&quot;query&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='query'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;What do you want to learn?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1a98afa-fa91-410b-b4c6-20ec07c20bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>566bc84d-0813-4c18-b1d6-99afbe26dc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>467b9093-eace-4c9b-91b9-6fa91579e206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>5236bbeb-ce78-449a-9717-0ba5c1b16a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What do you want to learn?</value>
      <webElementGuid>167ee60f-d0a2-4688-ad01-ca7f6a166d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-banner-area&quot;)/div[@class=&quot;container-xl&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col position-relative&quot;]/div[@class=&quot;home-banner-wrap&quot;]/form[@class=&quot;search-box-shadow&quot;]/div[@class=&quot;input-group search-box&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>bd2c92ef-26c3-470a-a139-96d314433fb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='query'])[2]</value>
      <webElementGuid>549e0f66-fdd3-40a4-bc0a-0fc8b2d1f7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home-banner-area']/div/div/div/div/form/div/input</value>
      <webElementGuid>28795384-5e49-477e-b2b4-93c2d57c5d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/form/div/input</value>
      <webElementGuid>a9f2ddc3-f736-40cb-90da-081f58ca9b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'query' and @placeholder = 'What do you want to learn?']</value>
      <webElementGuid>45d21b9d-d930-46f8-9ce6-4120418e045e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
